/*******************************************************************************
 *
 * Pentaho Big Data
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.runtime.test.test.impl;

import org.pentaho.runtime.test.RuntimeTest;
import org.pentaho.runtime.test.result.RuntimeTestEntrySeverity;
import org.pentaho.runtime.test.result.RuntimeTestResult;
import org.pentaho.runtime.test.result.RuntimeTestResultEntry;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Created by bryan on 8/12/15.
 */
public class RuntimeTestResultImpl implements RuntimeTestResult {
  private final RuntimeTest runtimeTest;
  private final List<RuntimeTestResultEntry> runtimeTestResultEntries;
  private final RuntimeTestEntrySeverity maxSeverity;
  private final long timeTaken;

  public RuntimeTestResultImpl( RuntimeTest runtimeTest, List<RuntimeTestResultEntry> runtimeTestResultEntries,
                                long timeTaken ) {
    this.runtimeTest = runtimeTest;
    this.runtimeTestResultEntries = Collections.unmodifiableList( new ArrayList<>( runtimeTestResultEntries ) );
    this.timeTaken = timeTaken;
    this.maxSeverity = RuntimeTestEntrySeverity.maxSeverityEntry( runtimeTestResultEntries );
  }

  @Override public RuntimeTestEntrySeverity getMaxSeverity() {
    return maxSeverity;
  }

  @Override public List<RuntimeTestResultEntry> getRuntimeTestResultEntries() {
    return runtimeTestResultEntries;
  }

  @Override public RuntimeTest getRuntimeTest() {
    return runtimeTest;
  }

  @Override public long getTimeTaken() {
    return timeTaken;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public String toString() {
    return "RuntimeTestResultImpl{" +
      "runtimeTest=" + runtimeTest +
      ", runtimeTestResultEntries=" + runtimeTestResultEntries +
      ", maxSeverity=" + maxSeverity +
      ", timeTaken=" + timeTaken +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
