/*******************************************************************************
 *
 * Pentaho Big Data
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.big.data.api.clusterTest.impl;

import org.pentaho.big.data.api.clusterTest.ClusterTestStatus;
import org.pentaho.big.data.api.clusterTest.module.ClusterTestModuleResults;

import java.util.List;

/**
 * Created by bryan on 8/18/15.
 */
public class ClusterTestStatusImpl implements ClusterTestStatus {
  private final List<ClusterTestModuleResults> clusterTestModuleResults;
  private final boolean done;

  public ClusterTestStatusImpl( List<ClusterTestModuleResults> clusterTestModuleResults, boolean done ) {
    this.clusterTestModuleResults = clusterTestModuleResults;
    this.done = done;
  }

  @Override public List<ClusterTestModuleResults> getModuleResults() {
    return clusterTestModuleResults;
  }

  @Override public boolean isDone() {
    return done;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public String toString() {
    return "ClusterTestStatusImpl{" +
      "clusterTestModuleResults=" + clusterTestModuleResults +
      ", done=" + done +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
