/*******************************************************************************
 *
 * Pentaho Big Data
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.big.data.api.clusterTest.module.impl;

import org.pentaho.big.data.api.clusterTest.module.ClusterTestModuleResults;
import org.pentaho.big.data.api.clusterTest.test.ClusterTest;
import org.pentaho.big.data.api.clusterTest.test.ClusterTestEntrySeverity;
import org.pentaho.big.data.api.clusterTest.test.ClusterTestResult;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Created by bryan on 8/11/15.
 */
public class ClusterTestModuleResultsImpl implements ClusterTestModuleResults {
  private final String name;
  private final List<ClusterTestResult> clusterTestResults;
  private final Set<ClusterTest> runningTests;
  private final Set<ClusterTest> outstandingTests;
  private final ClusterTestEntrySeverity maxSeverity;

  public ClusterTestModuleResultsImpl( String name, List<ClusterTestResult> clusterTestResults,
                                       Set<ClusterTest> runningTests, Set<ClusterTest> outstandingTests ) {
    this.name = name;
    this.runningTests = Collections.unmodifiableSet( new HashSet<>( runningTests ) );
    this.outstandingTests = Collections.unmodifiableSet( new HashSet<>( outstandingTests ) );
    this.clusterTestResults = Collections.unmodifiableList( new ArrayList<>( clusterTestResults ) );
    this.maxSeverity = ClusterTestEntrySeverity.maxSeverityResult( clusterTestResults );
  }

  @Override public String getName() {
    return name;
  }

  @Override public List<ClusterTestResult> getClusterTestResults() {
    return clusterTestResults;
  }

  @Override public ClusterTestEntrySeverity getMaxSeverity() {
    return maxSeverity;
  }

  @Override public Set<ClusterTest> getRunningTests() {
    return runningTests;
  }

  @Override public Set<ClusterTest> getOutstandingTests() {
    return outstandingTests;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public String toString() {
    return "ClusterTestModuleResultsImpl{" +
      "getName='" + name + '\'' +
      ", clusterTestResults=" + clusterTestResults +
      ", runningTests=" + runningTests +
      ", outstandingTests=" + outstandingTests +
      ", maxSeverity=" + maxSeverity +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
