/*******************************************************************************
 *
 * Pentaho Big Data
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.big.data.api.clusterTest.test.impl;

import org.pentaho.big.data.api.clusterTest.test.ClusterTestEntrySeverity;
import org.pentaho.big.data.api.clusterTest.test.ClusterTestResultEntry;

/**
 * Created by bryan on 8/12/15.
 */
public class ClusterTestResultEntryImpl implements ClusterTestResultEntry {
  private final ClusterTestEntrySeverity severity;
  private final String description;
  private final String message;
  private final Throwable exception;

  public ClusterTestResultEntryImpl( ClusterTestEntrySeverity severity, String description, String message ) {
    this( severity, description, message, null );
  }

  public ClusterTestResultEntryImpl( ClusterTestEntrySeverity severity, String description, String message,
                                     Throwable exception ) {
    this.severity = severity;
    this.description = description;
    this.message = message;
    this.exception = exception;
  }

  @Override public ClusterTestEntrySeverity getSeverity() {
    return severity;
  }

  @Override public String getDescription() {
    return description;
  }

  @Override public String getMessage() {
    return message;
  }

  @Override public Throwable getException() {
    return exception;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public String toString() {
    return "ClusterTestResultEntryImpl{" +
      "severity=" + severity +
      ", description='" + description + '\'' +
      ", message='" + message + '\'' +
      ", exception=" + exception +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
